version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: typing-postgres
    restart: always
    environment:
      POSTGRES_USER: navneetshukla
      POSTGRES_PASSWORD: terwtr@43$!&%$*12345#!&sq,.kjytcxae
      POSTGRES_DB: typing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: typing-go-app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: navneetshukla
      DB_PASSWORD: postgres
      DB_NAME: typing
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
