version: "3.8"

services:
  # --- MailHog Service ---
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"   # SMTP port
      - "8025:8025"   # Web UI port