apiVersion: v1
kind: Service
metadata:
  name: typing-speed-service-nodeport
  labels:
    app: typing-speed-service
spec:
  type: NodePort
  selector:
    app: typing-speed-pod

  ports:
    - protocol: TCP
      port: 
      targetPort:
      nodePort: 30080